### PR TITLE
Add support for multi-modal optimization using deterministic crowding and distance-derated fitness.

### PR DESCRIPTION
**Pull request by pcarranzav**
Partially based on how it's presented here: http://cadlab.mit.edu/publications/96-senin-tr9602-ga/dontindex/96-senin.pdf
There are also some other details I changed, please let me know if there's anything to correct/improve.
Cheers!

### CODE REVIEW

**Comment by spejman** [comment]
Thanks @pcarranzav ! Looks great and it's a cool improvement for the gem! Can you define methods with brackets ? Otherwise I'll do after merging.

Thanks!

**Comment by pcarranzav** [comment]
There it goes :)

**Comment by spejman** [comment]
Thanks @pcarranzav ! :+1:

**Comment by pcarranzav** [comment]
Thank you! This gem has been really useful.

**Comment by hstove** [comment]
Wow @pcarranzav, I just saw this, super cool! Thanks so much.

**Pull request merged**
