### PR TITLE
Quick fix to use #each_slice instead of #in_groups_of, as the latter is a Rails extension

### PR DESCRIPTION
**Pull request by benprew**
Sergio,

Thanks for writing this genetic algorithm gem.  I was hoping you could update the gem with my changes.

Also, if you're not maintaining the gem anymore, I'd be happy to take over maintenance for it.  (It looks like the last change was 4 years ago :) )

Thanks!

### CODE REVIEW

**Comment by spejman** [comment]
Thanks @benprew for your commit. Merging it! please feel free to create new pull requests with improvements I'll merge it ASAP and after that add you write perms to the repo.

**Comment by benprew** [comment]
Great, thanks @spejman for getting that merged in so quickly!

**Comment by igordeoliveirasa** [comment]
why am i getting the same mistake even after the mergint?

**Comment by benprew** [comment]
What is the error you're getting?

**Pull request merged**
